<?php

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Challenge;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = \Faker\Factory::create();
        $data = [
            [
                'role' => Admin(),
                'balance' => 1000.00,
                'is_premium' => 1,
                'name' => 'Admin User',
                'username' => 'admin',
                'email' => 'admin@idu.com',
                'password' => Hash::make('secret'),
                'is_admin' => true,
                'created_at' => now()
            ], [
                'role' => Normal(),
                'balance' => 1000.00,
                'is_premium' => 1,
                'name' => 'Test User 1',
                'username' => 'user1',
                'email' => 'user1@idu.com',
                'password' => Hash::make('secret'),
                'is_admin' => false,
                'created_at' => now()
            ], [
                'role' => Normal(),
                'balance' => 0.00,
                'is_premium' => 0,
                'name' => 'Test User 2',
                'username' => 'user2',
                'email' => 'user2@idu.com',
                'password' => Hash::make('secret'),
                'is_admin' => false,
                'created_at' => now()
            ], [
                'role' => Normal(),
                'balance' => 50.00,
                'is_premium' => 1,
                'name' => 'Test User 3',
                'username' => 'user3',
                'email' => 'user3@idu.com',
                'password' => Hash::make('secret'),
                'is_admin' => false,
                'created_at' => now()
            ]
        ];
        User::insert($data);
        $names = array(
            "Anderson",
            "Ashwoon",
            "Aikin",
            "Bateman",
            "Bongard",
            "Bowers",
            "Boyd",
            "Cannon",
            "Cast",
            "Deitz",
            "Dewalt",
            "Ebner",
            "Frick",
            "Hancock",
            "Haworth",
            "Hesch",
            "Hoffman",
            "Kassing",
            "Knutson",
            "Lawless",
            "Lawicki",
            "Mccord",
            "McCormack",
            "Miller",
            "Myers",
            "Nugent",
            "Ortiz",
            "Orwig",
            "Ory",
            "Paiser",
            "Pak",
            "Pettigrew",
            "Quinn",
            "Quizoz",
            "Ramachandran",
            "Resnick",
            "Sagar",
            "Schickowski",
            "Schiebel",
            "Sellon",
            "Severson",
            "Shaffer",
            "Solberg",
            "Soloman",
            "Sonderling",
            "Soukup",
            "Soulis",
            "Stahl",
            "Sweeney",
            "Tandy",
            "Trebil",
            "Trusela",
            "Trussel",
            "Turco",
            "Uddin",
            "Uflan",
            "Ulrich",
            "Upson",
            "Vader",
            "Vail",
            "Valente",
            "Van Zandt",
            "Vanderpoel",
            "Ventotla",
            "Vogal",
            "Wagle",
            "Wagner",
            "Wakefield",
            "Weinstein",
            "Weiss",
            "Woo",
            "Yang",
            "Yates",
            "Yocum",
            "Zeaser",
            "Zeller",
            "Ziegler",
            "Bauer",
            "Baxster",
            "Casal",
            "Cataldi",
            "Caswell",
            "Celedon",
            "Chambers",
            "Chapman",
            "Christensen",
            "Darnell",
            "Davidson",
            "Davis",
            "DeLorenzo",
            "Dinkins",
            "Doran",
            "Dugelman",
            "Dugan",
            "Duffman",
            "Eastman",
            "Ferro",
            "Ferry",
            "Fletcher",
            "Fietzer",
            "Hylan",
            "Hydinger",
            "Illingsworth",
            "Ingram",
            "Irwin",
            "Jagtap",
            "Jenson",
            "Johnson",
            "Johnsen",
            "Jones",
            "Jurgenson",
            "Kalleg",
            "Kaskel",
            "Keller",
            "Leisinger",
            "LePage",
            "Lewis",
            "Linde",
            "Lulloff",
            "Maki",
            "Martin",
            "McGinnis",
            "Mills",
            "Moody",
            "Moore",
            "Napier",
            "Nelson",
            "Norquist",
            "Nuttle",
            "Olson",
            "Ostrander",
            "Reamer",
            "Reardon",
            "Reyes",
            "Rice",
            "Ripka",
            "Roberts",
            "Rogers",
            "Root",
            "Sandstrom",
            "Sawyer",
            "Schlicht",
            "Schmitt",
            "Schwager",
            "Schutz",
            "Schuster",
            "Tapia",
            "Thompson",
            "Tiernan",
            "Tisler",
            "Adam",
            "Alex",
            "Aaron",
            "Ben",
            "Carl",
            "Dan",
            "David",
            "Edward",
            "Fred",
            "Frank",
            "George",
            "Hal",
            "Hank",
            "Ike",
            "John",
            "Jack",
            "Joe",
            "Larry",
            "Monte",
            "Matthew",
            "Mark",
            "Nathan",
            "Otto",
            "Paul",
            "Peter",
            "Roger",
            "Roger",
            "Steve",
            "Thomas",
            "Tim",
            "Ty",
            "Victor",
            "Walter",
            'Allison',
            'Arthur',
            'Ana',
            'Alex',
            'Arlene',
            'Alberto',
            'Barry',
            'Bertha',
            'Bill',
            'Bonnie',
            'Bret',
            'Beryl',
            'Chantal',
            'Cristobal',
            'Claudette',
            'Charley',
            'Cindy',
            'Chris',
            'Dean',
            'Dolly',
            'Danny',
            'Danielle',
            'Dennis',
            'Debby',
            'Erin',
            'Edouard',
            'Erika',
            'Earl',
            'Emily',
            'Ernesto',
            'Felix',
            'Fay',
            'Fabian',
            'Frances',
            'Franklin',
            'Florence',
            'Gabielle',
            'Gustav',
            'Grace',
            'Gaston',
            'Gert',
            'Gordon',
            'Humberto',
            'Hanna',
            'Henri',
            'Hermine',
            'Harvey',
            'Helene',
            'Iris',
            'Isidore',
            'Isabel',
            'Ivan',
            'Irene',
            'Isaac',
            'Jerry',
            'Josephine',
            'Juan',
            'Jeanne',
            'Jose',
            'Joyce',
            'Karen',
            'Kyle',
            'Kate',
            'Karl',
            'Katrina',
            'Kirk',
            'Lorenzo',
            'Lili',
            'Larry',
            'Lisa',
            'Lee',
            'Leslie',
            'Michelle',
            'Marco',
            'Mindy',
            'Maria',
            'Michael',
            'Noel',
            'Nana',
            'Nicholas',
            'Nicole',
            'Nate',
            'Nadine',
            'Olga',
            'Omar',
            'Odette',
            'Otto',
            'Ophelia',
            'Oscar',
            'Pablo',
            'Paloma',
            'Peter',
            'Paula',
            'Philippe',
            'Patty',
            'Rebekah',
            'Rene',
            'Rose',
            'Richard',
            'Rita',
            'Rafael',
            'Sebastien',
            'Sally',
            'Sam',
            'Shary',
            'Stan',
            'Sandy',
            'Tanya',
            'Teddy',
            'Teresa',
            'Tomas',
            'Tammy',
            'Tony',
            'Van',
            'Vicky',
            'Victor',
            'Virginie',
            'Vince',
            'Valerie',
            'Wendy',
            'Wilfred',
            'Wanda',
            'Walter',
            'Wilma',
            'William',
            'Kumiko',
            'Aki',
            'Miharu',
            'Chiaki',
            'Michiyo',
            'Itoe',
            'Nanaho',
            'Reina',
            'Emi',
            'Yumi',
            'Ayumi',
            'Kaori',
            'Sayuri',
            'Rie',
            'Miyuki',
            'Hitomi',
            'Naoko',
            'Miwa',
            'Etsuko',
            'Akane',
            'Kazuko',
            'Miyako',
            'Youko',
            'Sachiko',
            'Mieko',
            'Toshie',
            'Junko');
        for ($i=0; $i < 500; $i++) { 
            $data1[] = [
                'role' => Normal(),
                'balance' => 5000.00,
                'is_premium' => 1,
                'name' => $username[$i] = ucfirst($faker->randomElement($names)).' '.ucfirst($faker->randomElement($names)),
                'username' => $email[$i] = strtolower(str_replace(' ','-',$username[$i])).rand(2,99),
                'email' => strtolower($email[$i]).'@idu.com',
                'contact_number' => 123456789,
                'password' => Hash::make('secret'),
                'is_dummy' => true,
                'created_at' => now()
            ];
        }
        User::insert($data1);

    }
}
